from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class AnalysisStatus(str, Enum):
    """
    Status of the AI Analysis pipeline.
    """
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class RndBrief(BaseModel):
    """
    Structured 10-point Academic & Industrial R&D Brief generated by AI.
    """
    problem_statement: str = Field(description="1. Concise academic definition of the core challenge")
    current_situation: str = Field(description="2. On-ground field baseline and symptoms")
    key_challenges: List[str] = Field(default_factory=list, description="3. Engineering, geographical, or logistical hurdles")
    required_expertise: List[str] = Field(default_factory=list, description="4. Specific faculty & engineering squads required")
    suggested_research_area: List[str] = Field(default_factory=list, description="5. Academic thesis and R&D topics")
    suggested_technology_areas: List[str] = Field(default_factory=list, description="6. IoT, ML, hardware, bio-filtration toolkits")
    potential_solution_direction: List[str] = Field(default_factory=list, description="7. Pilot prototype architectures")
    stakeholders: List[str] = Field(default_factory=list, description="8. Beneficiaries, Line Departments, and Industry sponsors")
    expected_impact: str = Field(description="9. Measurable community and SDG outcome metrics")
    relevant_keywords: List[str] = Field(default_factory=list, description="10. Semantic tags for university squad pairing")


class AIAnalysisDocument(BaseModel):
    """
    MongoDB Document Schema for ai_analyses collection.
    """
    id: Optional[str] = Field(default=None, alias="_id")
    problem_id: str = Field(description="Linked Problem ObjectId string")

    # Classification & Severity
    category: str
    subcategory: Optional[str] = None
    priority: str = Field(description="LOW, MEDIUM, HIGH, CRITICAL")
    priority_reason: str = Field(description="AI explanation for assigned priority")
    confidence: float = Field(ge=0.0, le=1.0, description="Model confidence score (0.0 - 1.0)")
    problem_type: str = Field(description="e.g. ENVIRONMENTAL_HAZARD, INFRASTRUCTURE_DEFICIT, PUBLIC_HEALTH_RISK")
    affected_domain: str

    # Skill & Solution Suggestions
    required_expertise: List[str] = Field(default_factory=list)
    suggested_research_domains: List[str] = Field(default_factory=list)
    suggested_solution_areas: List[str] = Field(default_factory=list)

    # Duplicate & Similar Problem Detection
    similar_problem_ids: List[str] = Field(default_factory=list)
    duplicate_probability: float = Field(default=0.0, ge=0.0, le=1.0)
    similarity_reasons: Optional[List[str]] = Field(default_factory=list)

    # 10-Point R&D Brief
    rnd_brief: RndBrief

    # Execution Metadata
    status: AnalysisStatus = AnalysisStatus.COMPLETED
    provider: str = Field(default="gemini-2.0-flash", description="AI Provider / Engine identifier")
    is_fallback: bool = Field(default=False, description="True if generated via deterministic expert fallback")
    error_message: Optional[str] = None

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        populate_by_name = True
        json_encoders = {
            datetime: lambda dt: dt.isoformat()
        }
